#!/usr/bin/env python3

import tkinter as tk
from tkinter import filedialog, messagebox

root = tk.Tk()
root.title('Window')
root.attributes("-fullscreen", True)
root.attributes('-topmost', True)
root.state('zoomed')
root.configure(bg="#eee")
root.bind('<Escape>', lambda _: root.destroy())

text_area = tk.Text(
    root,
    font = ("Georgia", 30),
    highlightthickness = 0,
    borderwidth=0,
    highlightbackground = '#eee',
    border=0,
    highlightcolor ="#eee",
    background = '#eee',
    insertbackground="#aaa",
    insertwidth=10,
    fg = "#222"
)
text_area.pack(padx=400, pady=100, expand=True)
text_area.focus_set()


def open_file():
    root.withdraw()
    file_path = filedialog.askopenfilename(
        initialdir="/",
        title="Select a file",
        filetypes=(("Text files", ["*.bohdi", "*.md", "*.txt"]), ("All files", "*.*"))
    )
    if file_path:
        print(f"Selected file: {file_path}")
        text_area.delete(1.0, tk.END)
        file = open(file_path)
        content = file.read()
        file.close()
        text_area.insert(tk.END, content)
    root.deiconify()


def save_file():
    root.withdraw()
    file_path = filedialog.asksaveasfilename(
        defaultextension=".bohdi",
        filetypes=(("Text files", ["*.bohdi", "*.md", "*.txt"]), ("All files", "*.*")),
        title="Save Data"
    )
    if file_path:
        try:
            with open(file_path, 'w') as f:
                f.write(text_area.get('1.0', tk.END))
            messagebox.showinfo("Information", f"Data saved to: {file_path}")
        except Exception as e:
            messagebox.showinfo("Information", f"Data saved to: {file_path}")
    root.deiconify()


root.bind('<Control-o>', lambda _: open_file())
root.bind('<Control-s>', lambda _: save_file())


root.mainloop()